name: Build Windows EXE

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile Cricket_Shop_beta.py

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Cricket_Shop_beta_EXE
        path: dist/Cricket_Shop_beta.exe
